site_name: Test MkDocs

theme:
  name: material
  language: ru

nav:
    - Home: 'index.md'
    - 'User Guide':
        - 'Writing your docs': 'first.md'
        - 'Styling your docs': 'second.md'
    - About:
        - 'License': 'topic.html'
        - 'Release Notes': 'User_guide.md'