site_name: Test MkDocs

theme:
  name: material
  language: ru
  features:
    - navigation.indexes
    - content.tabs.link
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Руководство пользователя:
    - Основные понятия: Osnovnye_ponyatiya.md
    - О продукте: O_produkte.md
    - Требования к рабочему месту пользователя: Trebovaniya_k_rabochemu_mestu_polzovatelya.md
    - Аутентификация пользователя: Autentifikaciya_polzovatelya.md
    - Работа с приложением:
      - Основное меню: Osnovnoe_menu.md
      - Проекты:
        - Правила: Pravila.md
        - Профиль: Profile.md
        - Результаты сканирований: Rezultaty_skanirovanij.md
        - Запуск сканирования:
          - Запуск сканирования: Zapusk_skanirovaniya.md
          - Автоматическое сканирование: Avtomaticheskoe_skanirovanie.md
          - Ручное сканирование: Ruchnoe_skanirovanie.md
          - Запуск сканирования из командной строки: Zapusk_skanirovaniya_iz_komandnoj_stroki.md
          - Запуск сканирования из систем сборки: Zapusk_skanirovaniya_iz_sistem_sborki.md
        - Тест кейсы: Spisok_test_kejsov.md
        - Требования: Trebovaniya.md
        - Профиль пользователя: Profil_polzovatelya.md
        - Документация и рекомендации: Dokumentaciya_i_rekomendacii.md

plugins:
  - search:
      lang: # 
        - en
        - ru