site_name: Test MkDocs

theme:
  name: material
  language: ru

nav:
    - Home: 'index.md'
    - 'Руководство пользвателя':
        - 'Руководство пользователя': 'Rukovodstvo_polzovatelya.md'
        - 'О продукте': 'O_produkte.md'
    - About:
        - 'License': 'topic.html'
        - 'Release Notes': 'User_guide.md'