site_name: Test MkDocs

theme:
  name: material
  language: ru
  features:
    - navigation.indexes

nav:
  - content.tabs.link
  - navigation.instant


plugins:
  - search:
      lang: # 
        - en
        - ru