site_name: Test MkDocs
theme:
  name: material
  language: ru
  custom_dir: overrides
  palette: # 
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate # 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  analytics:
    provider: google
    property: G-26CL0JRJFS
  consent:
    title: Cookie consent
    description: >- # 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- # 


            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.

